# Generated by Django 4.1.7 on 2023-02-24 23:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('dateCreated', models.DateField(auto_created=True, auto_now_add=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.CharField(default='Content', max_length=1000)),
                ('userKey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postCreatedByUser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('dateCreated', models.DateField(auto_created=True, auto_now_add=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('postKey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likeLinkedToPost', to='network.post')),
                ('userKey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likeCreatedByUser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('dateCreated', models.DateField(auto_created=True, auto_now_add=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('createdByUserKey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followCreatedByUser', to=settings.AUTH_USER_MODEL)),
                ('followingUserKey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followLinkedToUser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
